[package]
name = "hk_modlinks_history"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
handlebars = "4.5.0"
itertools = "0.12.0"
ureq = "2.9.1"

[dependencies.hk_modlinks]
git = "https://github.com/Clazex/hk_modlinks"
rev = "99d60a8"
features = ["json", "changelog-template"]
